# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_WordCloud_pyqt.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1155, 833)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1155, 833))
        MainWindow.setMaximumSize(QtCore.QSize(1155, 833))
        font = QtGui.QFont()
        font.setPointSize(8)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/images/动物/可达鸭.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolTip("")
        MainWindow.setStyleSheet("#centralwidget\n"
"{\n"
"background-color: rgb(245, 245, 247);\n"
"}\n"
"#groupbox\n"
"{\n"
"background-color: rgb(255, 255, 127);\n"
"}\n"
".QPushButton{\n"
"border-radius: 10px;  \n"
"border: 2px groove gray; \n"
"border-style: outset;\n"
"\n"
"}\n"
"\n"
"\n"
"")
        MainWindow.setIconSize(QtCore.QSize(50, 50))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QPushButton{\n"
"border-radius: 10px;  \n"
"border: 2px groove gray; \n"
"border-style: outset;\n"
"    background-color: rgb(0, 170, 255);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1151, 821))
        self.tabWidget.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setStyleSheet("")
        self.tab.setObjectName("tab")
        self.toolBox = QtWidgets.QToolBox(self.tab)
        self.toolBox.setGeometry(QtCore.QRect(0, 0, 331, 781))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.toolBox.setFont(font)
        self.toolBox.setStyleSheet("")
        self.toolBox.setObjectName("toolBox")
        self.common = QtWidgets.QWidget()
        self.common.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.common.setObjectName("common")
        self.groupBox = QtWidgets.QGroupBox(self.common)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 331, 661))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 255, 203, 211), stop:1 rgba(255, 255, 255, 255));")
        self.groupBox.setTitle("")
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.txtlineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.txtlineEdit.setGeometry(QtCore.QRect(120, 50, 161, 31))
        self.txtlineEdit.setObjectName("txtlineEdit")
        self.flieButton = QtWidgets.QPushButton(self.groupBox)
        self.flieButton.setGeometry(QtCore.QRect(10, 47, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.flieButton.setFont(font)
        self.flieButton.setStyleSheet("")
        self.flieButton.setObjectName("flieButton")
        self.imglineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.imglineEdit.setGeometry(QtCore.QRect(120, 110, 161, 31))
        self.imglineEdit.setObjectName("imglineEdit")
        self.imgButton = QtWidgets.QPushButton(self.groupBox)
        self.imgButton.setGeometry(QtCore.QRect(10, 107, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.imgButton.setFont(font)
        self.imgButton.setStyleSheet("")
        self.imgButton.setObjectName("imgButton")
        self.saveButton = QtWidgets.QPushButton(self.groupBox)
        self.saveButton.setGeometry(QtCore.QRect(149, 213, 111, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.saveButton.setFont(font)
        self.saveButton.setStyleSheet("border-top-color: rgb(0, 0, 0);")
        self.saveButton.setObjectName("saveButton")
        self.plotButton = QtWidgets.QPushButton(self.groupBox)
        self.plotButton.setGeometry(QtCore.QRect(11, 213, 101, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.plotButton.setFont(font)
        self.plotButton.setStyleSheet("")
        self.plotButton.setObjectName("plotButton")
        self.toolBox.addItem(self.common, "")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.page.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.page.setAcceptDrops(False)
        self.page.setObjectName("page")
        self.groupBox_3 = QtWidgets.QGroupBox(self.page)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 0, 331, 661))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 255, 203, 211), stop:1 rgba(255, 255, 255, 255));")
        self.groupBox_3.setObjectName("groupBox_3")
        self.stopwords = QtWidgets.QTextEdit(self.groupBox_3)
        self.stopwords.setGeometry(QtCore.QRect(10, 30, 301, 301))
        self.stopwords.setObjectName("stopwords")
        self.toolBox.addItem(self.page, "")
        self.advanced = QtWidgets.QWidget()
        self.advanced.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.advanced.setObjectName("advanced")
        self.groupBox_2 = QtWidgets.QGroupBox(self.advanced)
        self.groupBox_2.setGeometry(QtCore.QRect(0, -10, 331, 661))
        self.groupBox_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 255, 203, 211), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.Templatecolor = QtWidgets.QCheckBox(self.groupBox_2)
        self.Templatecolor.setGeometry(QtCore.QRect(20, 20, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Templatecolor.setFont(font)
        self.Templatecolor.setAutoFillBackground(False)
        self.Templatecolor.setChecked(True)
        self.Templatecolor.setObjectName("Templatecolor")
        self.FoncobotBox = QtWidgets.QComboBox(self.groupBox_2)
        self.FoncobotBox.setGeometry(QtCore.QRect(200, 20, 87, 22))
        self.FoncobotBox.setObjectName("FoncobotBox")
        self.FoncobotBox.addItem("")
        self.FoncobotBox.addItem("")
        self.FoncobotBox.addItem("")
        self.FoncobotBox.addItem("")
        self.mytips = QtWidgets.QTextEdit(self.groupBox_2)
        self.mytips.setGeometry(QtCore.QRect(20, 490, 291, 51))
        self.mytips.setObjectName("mytips")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 150, 231, 24))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox.setWrapping(False)
        self.spinBox.setMaximum(500)
        self.spinBox.setProperty("value", 200)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 200, 231, 24))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.scale = QtWidgets.QSpinBox(self.layoutWidget1)
        self.scale.setMinimum(1)
        self.scale.setMaximum(20)
        self.scale.setProperty("value", 2)
        self.scale.setObjectName("scale")
        self.horizontalLayout_2.addWidget(self.scale)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 60, 231, 24))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.width = QtWidgets.QSpinBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.width.setFont(font)
        self.width.setMaximum(2000)
        self.width.setProperty("value", 1000)
        self.width.setObjectName("width")
        self.horizontalLayout_3.addWidget(self.width)
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget3.setGeometry(QtCore.QRect(20, 100, 231, 24))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.height = QtWidgets.QSpinBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.height.setFont(font)
        self.height.setMaximum(2000)
        self.height.setProperty("value", 1000)
        self.height.setObjectName("height")
        self.horizontalLayout_4.addWidget(self.height)
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget4.setGeometry(QtCore.QRect(20, 240, 231, 24))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.contour_width = QtWidgets.QSpinBox(self.layoutWidget4)
        self.contour_width.setMaximum(5)
        self.contour_width.setObjectName("contour_width")
        self.horizontalLayout_5.addWidget(self.contour_width)
        self.layoutWidget5 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget5.setGeometry(QtCore.QRect(20, 280, 291, 24))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.relative_scaling = QtWidgets.QDoubleSpinBox(self.layoutWidget5)
        self.relative_scaling.setDecimals(1)
        self.relative_scaling.setMaximum(1.0)
        self.relative_scaling.setSingleStep(0.1)
        self.relative_scaling.setProperty("value", 0.5)
        self.relative_scaling.setObjectName("relative_scaling")
        self.horizontalLayout_6.addWidget(self.relative_scaling)
        self.layoutWidget6 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget6.setGeometry(QtCore.QRect(20, 320, 391, 90))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.colormap = QtWidgets.QComboBox(self.layoutWidget6)
        self.colormap.setInsertPolicy(QtWidgets.QComboBox.InsertAtCurrent)
        self.colormap.setIconSize(QtCore.QSize(295, 60))
        self.colormap.setObjectName("colormap")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/color/bg/viridis.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.colormap.addItem(icon1, "")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/color/bg/plasma.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.colormap.addItem(icon2, "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/color/bg/inferno.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.colormap.addItem(icon3, "")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/color/bg/magma.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.colormap.addItem(icon4, "")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/color/bg/cividis.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.colormap.addItem(icon5, "")
        self.verticalLayout.addWidget(self.colormap)
        self.layoutWidget7 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget7.setGeometry(QtCore.QRect(30, 430, 271, 31))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.plotButton_2 = QtWidgets.QPushButton(self.layoutWidget7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.plotButton_2.setFont(font)
        self.plotButton_2.setStyleSheet("border-radius: 10px;  \n"
"border: 2px groove gray; \n"
"border-style: outset;")
        self.plotButton_2.setObjectName("plotButton_2")
        self.horizontalLayout_7.addWidget(self.plotButton_2)
        self.saveButton_2 = QtWidgets.QPushButton(self.layoutWidget7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.saveButton_2.setFont(font)
        self.saveButton_2.setStyleSheet("border-radius: 10px;  \n"
"border: 2px groove gray; \n"
"border-style: outset;")
        self.saveButton_2.setObjectName("saveButton_2")
        self.horizontalLayout_7.addWidget(self.saveButton_2)
        self.toolBox.addItem(self.advanced, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 331, 653))
        self.page_2.setObjectName("page_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 0, 331, 651))
        self.groupBox_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 255, 203, 211), stop:1 rgba(255, 255, 255, 255));")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.StatisWordFreq = QtWidgets.QCheckBox(self.groupBox_4)
        self.StatisWordFreq.setGeometry(QtCore.QRect(20, 10, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.StatisWordFreq.setFont(font)
        self.StatisWordFreq.setAutoFillBackground(False)
        self.StatisWordFreq.setChecked(False)
        self.StatisWordFreq.setObjectName("StatisWordFreq")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 370, 271, 31))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.plotButton_4 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.plotButton_4.setFont(font)
        self.plotButton_4.setStyleSheet("border-radius: 10px;  \n"
"border: 2px groove gray; \n"
"border-style: outset;")
        self.plotButton_4.setObjectName("plotButton_4")
        self.horizontalLayout_9.addWidget(self.plotButton_4)
        self.saveButton_3 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.saveButton_3.setFont(font)
        self.saveButton_3.setStyleSheet("border-radius: 10px;  \n"
"border: 2px groove gray; \n"
"border-style: outset;")
        self.saveButton_3.setObjectName("saveButton_3")
        self.horizontalLayout_9.addWidget(self.saveButton_3)
        self.toolBox.addItem(self.page_2, "")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_2.setGeometry(QtCore.QRect(330, 0, 821, 781))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.customwidget = MatplotlibWidget(self.tab_3)
        self.customwidget.setGeometry(QtCore.QRect(0, 0, 811, 751))
        self.customwidget.setStyleSheet("background-color: rgb(250, 238, 255);")
        self.customwidget.setObjectName("customwidget")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.statistics = MatplotlibWidget(self.tab_4)
        self.statistics.setGeometry(QtCore.QRect(0, 0, 811, 751))
        self.statistics.setStyleSheet("background-color: rgb(250, 238, 255);")
        self.statistics.setObjectName("statistics")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1155, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        self.menu.setFont(font)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(3)
        self.tabWidget_2.setCurrentIndex(0)
        self.flieButton.clicked.connect(MainWindow.textbutton)
        self.imgButton.clicked.connect(MainWindow.imagebutton)
        self.plotButton.clicked.connect(MainWindow.Cloudplot)
        self.saveButton.clicked.connect(MainWindow.saveimg)
        self.plotButton_2.clicked.connect(MainWindow.Cloudplot)
        self.saveButton_2.clicked.connect(MainWindow.saveimg)
        self.colormap.currentIndexChanged['QString'].connect(MainWindow.colorchanged)
        self.plotButton_4.clicked.connect(MainWindow.Cloudplot)
        self.saveButton_3.clicked.connect(MainWindow.saveimg)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.flieButton.setText(_translate("MainWindow", "选择词源"))
        self.imgButton.setText(_translate("MainWindow", "选择图片"))
        self.saveButton.setText(_translate("MainWindow", "保存"))
        self.plotButton.setText(_translate("MainWindow", "绘制"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.common), _translate("MainWindow", "词源选择"))
        self.groupBox_3.setTitle(_translate("MainWindow", "请输入不想在词云中出现的词语"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "屏蔽词"))
        self.Templatecolor.setText(_translate("MainWindow", "按照模板颜色绘图"))
        self.FoncobotBox.setItemText(0, _translate("MainWindow", "宋体"))
        self.FoncobotBox.setItemText(1, _translate("MainWindow", "楷体"))
        self.FoncobotBox.setItemText(2, _translate("MainWindow", "行书"))
        self.FoncobotBox.setItemText(3, _translate("MainWindow", "Courier New"))
        self.label_2.setText(_translate("MainWindow", "最大词数"))
        self.label.setText(_translate("MainWindow", "缩放倍数"))
        self.label_3.setText(_translate("MainWindow", "轮廓宽度"))
        self.label_4.setText(_translate("MainWindow", "轮廓高度"))
        self.label_5.setText(_translate("MainWindow", "轮廓宽度"))
        self.label_6.setText(_translate("MainWindow", "词频与字体大小相关性"))
        self.label_7.setText(_translate("MainWindow", "选择配色"))
        self.colormap.setItemText(0, _translate("MainWindow", "viridis"))
        self.colormap.setItemText(1, _translate("MainWindow", "plasma"))
        self.colormap.setItemText(2, _translate("MainWindow", "inferno"))
        self.colormap.setItemText(3, _translate("MainWindow", "magma"))
        self.colormap.setItemText(4, _translate("MainWindow", "cividis"))
        self.plotButton_2.setText(_translate("MainWindow", "绘制"))
        self.saveButton_2.setText(_translate("MainWindow", "保存"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.advanced), _translate("MainWindow", "高级设置"))
        self.StatisWordFreq.setText(_translate("MainWindow", "根据统计词频绘图"))
        self.plotButton_4.setText(_translate("MainWindow", "绘制"))
        self.saveButton_3.setText(_translate("MainWindow", "保存"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "统计分析"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "词云"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "统计"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "词云图"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "可视化"))
        self.menu.setTitle(_translate("MainWindow", "帮助"))
from matplotlibwidget import MatplotlibWidget
import wcqt_rc
